spring:
  application:
    name: community

  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: ture

  data:
    redis:
      host: localhost
      port: 6379
      password:

  thymeleaf:
    cache: true

jwt:
  expirationtime:
#    accessTime: 216000
    accessTime: 21600000
    refreshTime: 21600000
  secret: ${JWT_SECRET:defaultfordevalsjfielsjfinaajfowinblxiejfwoihbya}


logging:
  level:
    org.hibernate.SQL: debug

